import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f6f4ee',
  },
  keyboardAvoiding: {
    flex: 1,
  },
  content: {
    padding: 22,
    paddingBottom: 20,
  },
  homeContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingBottom: 20,
  },
  homeContentCompact: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 16,
  },
  homeTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  languagePickerCompact: {
    backgroundColor: '#e7e5df',
    borderRadius: 10,
    flexDirection: 'row',
    padding: 3,
  },
  languageOptionCompact: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  languageOptionCompactText: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '900',
  },
  addContent: {
    flex: 1,
    padding: 22,
    paddingBottom: 0,
    position: 'relative',
  },
  addContentCompact: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 0,
  },
  listContent: {
    padding: 22,
    paddingBottom: 20,
  },
  listHeader: {
    marginBottom: 18,
  },
  eyebrow: {
    color: '#0f766e',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 9,
    textTransform: 'uppercase',
  },
  homeEyebrowCompact: {
    marginBottom: 5,
  },
  title: {
    color: '#111827',
    fontSize: 31,
    fontWeight: '900',
    lineHeight: 38,
    marginBottom: 12,
  },
  homeTitleCompact: {
    fontSize: 27,
    lineHeight: 39,
    marginBottom: 6,
  },
  stepTitle: {
    color: '#111827',
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 33,
    marginBottom: 6,
  },
  stepTitleCompact: {
    fontSize: 24,
    lineHeight: 29,
    marginBottom: 4,
  },
  stepBody: {
    color: '#4b5563',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  body: {
    color: '#4b5563',
    fontSize: 16,
    lineHeight: 24,
  },
  homeCheckPanel: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    marginBottom: 16,
    marginTop: 18,
    padding: 16,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.06,
    shadowRadius: 16,
  },
  homeCheckPanelCompact: {
    marginBottom: 12,
    marginTop: 10,
    padding: 13,
  },
  homeCheckTitle: {
    color: '#111827',
    fontSize: 19,
    fontWeight: '900',
    lineHeight: 26,
  },
  homeCheckText: {
    color: '#4b5563',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
    marginTop: 4,
  },
  homeCheckItem: {
    borderColor: '#e5e7eb',
    borderTopWidth: 1,
    marginTop: 13,
    paddingTop: 13,
  },
  homeCheckName: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
  },
  homeCheckMeta: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 3,
  },
  homeCheckActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  homeKeepButton: {
    alignItems: 'center',
    backgroundColor: '#0f766e',
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 10,
  },
  homeKeepButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
    includeFontPadding: false,
  },
  homeSlipButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ed',
    borderColor: '#e08a3c',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 10,
  },
  homeSlipButtonText: {
    color: '#9a4f12',
    fontSize: 13,
    fontWeight: '900',
    includeFontPadding: false,
  },
  homeStartButtonWrap: {
    marginTop: 18,
  },
  homeStartButtonWrapCompact: {
    marginTop: 12,
  },
  homeStartButton: {
    alignItems: 'center',
    backgroundColor: '#e7f4ef',
    borderColor: '#0f766e',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 64,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#0f766e',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.16,
    shadowRadius: 14,
  },
  homeStartIcon: {
    alignItems: 'center',
    backgroundColor: '#0f766e',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  homeStartTitle: {
    color: '#0f766e',
    fontSize: 19,
    fontWeight: '900',
  },
  homeStartText: {
    color: '#4b5563',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 2,
  },
  summaryPanel: {
    backgroundColor: '#e7f4ef',
    borderRadius: 16,
    marginTop: 24,
    padding: 18,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  summaryPanelCompact: {
    marginTop: 14,
    padding: 14,
  },
  summaryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryKicker: {
    color: '#0f766e',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 5,
    textTransform: 'uppercase',
  },
  summaryTitle: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '900',
  },
  summaryIcon: {
    alignItems: 'center',
    backgroundColor: '#0f766e',
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  summaryRows: {
    borderColor: '#b9d9d2',
    borderTopWidth: 1,
    marginTop: 16,
    paddingTop: 12,
  },
  summaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 30,
    paddingVertical: 7,
  },
  summaryLabel: {
    color: '#4b5563',
    fontSize: 12,
    fontWeight: '700',
    flexShrink: 0,
    includeFontPadding: false,
    width: 178,
  },
  summaryValue: {
    color: '#0f766e',
    flex: 1,
    fontSize: 13,
    fontWeight: '900',
    includeFontPadding: false,
    textAlign: 'right',
  },
  healthInsightCard: {
    alignItems: 'flex-start',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
    padding: 14,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  healthInsightIcon: {
    alignItems: 'center',
    backgroundColor: '#e7f4ef',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  healthInsightKicker: {
    color: '#0f766e',
    fontSize: 11,
    fontWeight: '900',
    marginBottom: 3,
    textTransform: 'uppercase',
  },
  healthInsightTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
  },
  healthInsightText: {
    color: '#4b5563',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 4,
  },
  notePanel: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    marginTop: 24,
    padding: 18,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  helpPanel: {
    alignItems: 'flex-start',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
    padding: 16,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  panelTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 7,
  },
  panelText: {
    color: '#4b5563',
    fontSize: 15,
    lineHeight: 22,
  },
  helperText: {
    color: '#6b7280',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
    marginBottom: 10,
    marginTop: -2,
  },
  quickStartCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    marginTop: 12,
    padding: 16,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  quickStartKicker: {
    color: '#e08a3c',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 5,
    textTransform: 'uppercase',
  },
  quickStartTitle: {
    color: '#111827',
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 27,
  },
  quickStartMeta: {
    color: '#4b5563',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 19,
    marginTop: 6,
  },
  safetyNote: {
    alignItems: 'flex-start',
    backgroundColor: '#fff7ed',
    borderColor: '#fed7aa',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    marginTop: 14,
    padding: 12,
  },
  safetyNoteText: {
    color: '#9a4f12',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 19,
  },
  label: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 9,
    marginTop: 24,
  },
  stepLabel: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
    marginTop: 14,
  },
  stepLabelCompact: {
    marginBottom: 6,
    marginTop: 10,
  },
  stageBar: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  stageBarCompact: {
    marginTop: 10,
  },
  stageDot: {
    backgroundColor: '#d1d5db',
    borderRadius: 8,
    flex: 1,
    height: 6,
  },
  stageDotActive: {
    backgroundColor: '#0f766e',
  },
  stagePanel: {
    marginTop: 6,
  },
  stagePanelFill: {
    flex: 1,
  },
  stageScroll: {
    flex: 1,
  },
  stageScrollContent: {
    flexGrow: 1,
    paddingBottom: 18,
  },
  stageScrollContentKeyboardOpen: {
    paddingBottom: 36,
  },
  optionList: {
    gap: 12,
  },
  optionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 10,
    rowGap: 10,
  },
  optionTile: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#d1d5db',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 74,
    paddingHorizontal: 10,
    paddingVertical: 10,
    width: '48.4%',
  },
  optionTileCompact: {
    gap: 8,
    minHeight: 64,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  subtypeTile: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#d1d5db',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 58,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: '48.4%',
  },
  subtypeTileCompact: {
    minHeight: 48,
    paddingVertical: 6,
  },
  optionRow: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#d1d5db',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 66,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  optionRowCompact: {
    minHeight: 58,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  optionRowSelected: {
    backgroundColor: '#e7f4ef',
    borderColor: '#0f766e',
  },
  optionIcon: {
    alignItems: 'center',
    backgroundColor: '#e7f4ef',
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  optionIconSelected: {
    backgroundColor: '#0f766e',
  },
  optionTextBlock: {
    flex: 1,
  },
  optionTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  optionTitleSelected: {
    color: '#0f766e',
  },
  optionMeta: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  stepActions: {
    columnGap: 10,
    flexDirection: 'row',
    marginTop: 14,
  },
  fixedStepActions: {
    backgroundColor: '#f6f4ee',
    borderColor: '#d9e3df',
    borderTopWidth: 1,
    columnGap: 10,
    flexDirection: 'row',
    marginHorizontal: -22,
    marginTop: 8,
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 12,
  },
  fixedStepActionsCompact: {
    marginHorizontal: -16,
    paddingHorizontal: 16,
  },
  optionalPanel: {
    marginTop: 4,
  },
  stepActionButton: {
    width: '48.4%',
  },
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    backgroundColor: '#ffffff',
    borderColor: '#d1d5db',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  chipSelected: {
    backgroundColor: '#0f766e',
    borderColor: '#0f766e',
  },
  chipText: {
    color: '#374151',
    fontSize: 14,
    fontWeight: '800',
  },
  chipTextSelected: {
    color: '#ffffff',
  },
  subChip: {
    backgroundColor: '#ffffff',
    borderColor: '#d9e3df',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  subChipSelected: {
    backgroundColor: '#e7f4ef',
    borderColor: '#0f766e',
  },
  subChipText: {
    color: '#374151',
    fontSize: 14,
    fontWeight: '700',
  },
  subChipTextSelected: {
    color: '#0f766e',
  },
  input: {
    backgroundColor: '#ffffff',
    borderColor: '#d1d5db',
    borderRadius: 8,
    borderWidth: 1,
    color: '#111827',
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  customSubtypeBox: {
    backgroundColor: '#ffffff',
    borderColor: '#e5e7eb',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 10,
    padding: 10,
  },
  customSubtypeLabel: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  customSubtypeActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  customSubtypeInput: {
    backgroundColor: '#ffffff',
    borderColor: '#d1d5db',
    borderRadius: 8,
    borderWidth: 1,
    color: '#111827',
    flex: 1,
    fontSize: 16,
    minHeight: 46,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  customSubtypeAddButton: {
    alignItems: 'center',
    backgroundColor: '#0f766e',
    borderRadius: 8,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  customSubtypeChipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  customSubtypeChip: {
    alignItems: 'center',
    backgroundColor: '#e7f4ef',
    borderColor: '#0f766e',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    maxWidth: '100%',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  customSubtypeChipText: {
    color: '#0f766e',
    fontSize: 13,
    fontWeight: '900',
    maxWidth: 210,
  },
  milestoneOptionList: {
    gap: 9,
  },
  milestoneOption: {
    backgroundColor: '#ffffff',
    borderColor: '#d1d5db',
    borderRadius: 8,
    borderWidth: 1,
    padding: 11,
  },
  milestoneOptionSelected: {
    backgroundColor: '#e7f4ef',
    borderColor: '#0f766e',
  },
  milestoneOptionMain: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  milestoneOptionTitle: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '900',
  },
  milestoneOptionTitleSelected: {
    color: '#0f766e',
  },
  milestoneOptionSubtitle: {
    color: '#6b7280',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 2,
  },
  milestoneInfoButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 5,
    marginTop: 9,
    paddingVertical: 3,
  },
  milestoneInfoButtonText: {
    color: '#0f766e',
    fontSize: 13,
    fontWeight: '900',
  },
  milestoneOptionBody: {
    color: '#4b5563',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 7,
  },
  dateBox: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#0f766e',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dateBoxLabel: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  dateBoxTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  dateBoxValue: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
  },
  dateBoxHint: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  dateModalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(17, 24, 39, 0.42)',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  datePopover: {
    backgroundColor: '#ffffff',
    borderColor: '#d9e3df',
    borderRadius: 18,
    borderWidth: 1,
    maxWidth: 390,
    padding: 16,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: 14,
    },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    width: '100%',
  },
  datePopoverHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  datePopoverTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '900',
  },
  dateCloseButton: {
    alignItems: 'center',
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  webDateShell: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#0f766e',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  webDateInput: {
    borderWidth: 0,
    color: '#111827',
    flex: 1,
    fontSize: 16,
    fontWeight: '900',
    paddingVertical: 8,
  },
  webDateHint: {
    color: '#6b7280',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 8,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#111827',
    borderRadius: 8,
    marginTop: 24,
    paddingVertical: 15,
  },
  primaryButtonInline: {
    alignItems: 'center',
    backgroundColor: '#111827',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 14,
    width: '48.4%',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
    includeFontPadding: false,
    textAlign: 'center',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#e7f4ef',
    borderRadius: 8,
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: '#0f766e',
    fontSize: 15,
    fontWeight: '900',
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: '#f3f4f6',
    borderColor: '#d1d5db',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 14,
    width: '48.4%',
  },
  backButtonText: {
    color: '#374151',
    fontSize: 15,
    fontWeight: '900',
  },
  nextButton: {
    alignItems: 'center',
    backgroundColor: '#111827',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 14,
    width: '48.4%',
  },
  nextButtonFull: {
    alignItems: 'center',
    backgroundColor: '#111827',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 14,
    width: '100%',
  },
  nextButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
    includeFontPadding: false,
    textAlign: 'center',
  },
  notePanelCompact: {
    backgroundColor: '#ffffff',
    borderColor: '#d9e3df',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 12,
    padding: 16,
  },
  notePanelCompactTight: {
    marginTop: 10,
    padding: 12,
  },
  progressCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    marginBottom: 14,
    padding: 16,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  cardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  cardTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  cardTitle: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '900',
  },
  cardSubtitle: {
    color: '#6b7280',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 3,
  },
  compactProgressRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  compactProgressItem: {
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    flex: 1,
    padding: 10,
  },
  compactProgressValue: {
    color: '#0f766e',
    fontSize: 16,
    fontWeight: '900',
  },
  compactProgressLabel: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  cardStreakRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  cardStreakNumber: {
    color: '#0f766e',
    fontSize: 44,
    fontWeight: '900',
    includeFontPadding: false,
    minWidth: 54,
  },
  cardStreakTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  cardStreakLabel: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '900',
  },
  cardMilestoneLine: {
    color: '#6b7280',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 3,
  },
  cardProgressTrack: {
    backgroundColor: '#d9e3df',
    borderRadius: 999,
    height: 8,
    marginTop: 12,
    overflow: 'hidden',
  },
  cardProgressFill: {
    backgroundColor: '#e08a3c',
    borderRadius: 999,
    height: '100%',
  },
  moneyChip: {
    backgroundColor: '#fff7ed',
    borderRadius: 8,
    color: '#9a4f12',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  daysPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#ecfdf5',
    borderRadius: 8,
    color: '#047857',
    flexShrink: 0,
    fontSize: 14,
    fontWeight: '900',
    minWidth: 68,
    overflow: 'hidden',
    paddingHorizontal: 11,
    paddingVertical: 7,
    textAlign: 'center',
  },
  metric: {
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    flex: 1,
    padding: 12,
  },
  metricValue: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '900',
  },
  metricLabel: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  cardText: {
    color: '#4b5563',
    fontSize: 14,
    marginTop: 16,
  },
  cardActions: {
    columnGap: 10,
    flexDirection: 'row',
    marginTop: 15,
  },
  resetButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ed',
    borderRadius: 8,
    flex: 1,
    paddingVertical: 12,
  },
  resetButtonText: {
    color: '#c2410c',
    fontSize: 14,
    fontWeight: '900',
  },
  deleteButton: {
    alignItems: 'center',
    backgroundColor: '#fff1f2',
    borderRadius: 8,
    columnGap: 6,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  deleteButtonText: {
    color: '#be123c',
    fontSize: 14,
    fontWeight: '900',
  },
  emptyState: {
    backgroundColor: '#ffffff',
    borderColor: '#e5e7eb',
    borderRadius: 8,
    borderWidth: 1,
    padding: 18,
  },
  modalBackdrop: {
    backgroundColor: 'rgba(17, 24, 39, 0.55)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    padding: 22,
  },
  detailPage: {
    backgroundColor: '#f6f4ee',
    flex: 1,
  },
  detailPageHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 10,
  },
  backIconButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#d9e3df',
    borderRadius: 8,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  detailContent: {
    paddingHorizontal: 18,
    paddingBottom: 20,
  },
  detailKicker: {
    color: '#0f766e',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  detailTitle: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 27,
  },
  detailHero: {
    backgroundColor: '#e7f4ef',
    borderRadius: 18,
    padding: 20,
  },
  detailHeroDays: {
    color: '#0f766e',
    fontSize: 48,
    fontWeight: '900',
  },
  detailHeroText: {
    color: '#4b5563',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 2,
  },
  detailMetricGrid: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  detailMetric: {
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    flex: 1,
    padding: 11,
  },
  moneyInsightBox: {
    alignItems: 'flex-start',
    backgroundColor: '#fff7ed',
    borderRadius: 14,
    flexDirection: 'row',
    gap: 9,
    marginTop: 10,
    padding: 12,
  },
  moneyInsightText: {
    color: '#9a4f12',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 19,
  },
  detailSection: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    marginTop: 12,
    padding: 14,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  detailSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  detailSectionTitle: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '900',
  },
  detailSectionMeta: {
    color: '#0f766e',
    fontSize: 13,
    fontWeight: '900',
  },
  detailText: {
    color: '#4b5563',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 8,
  },
  detailInputLabel: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 6,
    marginTop: 12,
    textTransform: 'uppercase',
  },
  editButton: {
    alignItems: 'center',
    backgroundColor: '#e7f4ef',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  editButtonText: {
    color: '#0f766e',
    fontSize: 13,
    fontWeight: '900',
  },
  milestoneTrack: {
    backgroundColor: '#d9e3df',
    borderRadius: 8,
    height: 10,
    marginTop: 12,
    overflow: 'hidden',
  },
  milestoneFill: {
    backgroundColor: '#0f766e',
    borderRadius: 8,
    height: '100%',
  },
  nextMilestoneBox: {
    backgroundColor: '#e7f4ef',
    borderRadius: 8,
    marginTop: 12,
    padding: 12,
  },
  nextMilestoneTitle: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 9,
  },
  nextMilestoneGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  nextMilestoneButton: {
    backgroundColor: '#0f766e',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  nextMilestoneButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
  nextHealthBox: {
    backgroundColor: '#e7f4ef',
    borderRadius: 12,
    marginTop: 12,
    padding: 12,
  },
  nextHealthKicker: {
    color: '#0f766e',
    fontSize: 11,
    fontWeight: '900',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  nextHealthTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '900',
  },
  healthItem: {
    alignItems: 'flex-start',
    borderColor: '#e5e7eb',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
    paddingTop: 12,
    opacity: 0.62,
  },
  healthItemUnlocked: {
    opacity: 1,
  },
  healthDayBadge: {
    alignItems: 'center',
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  healthDayBadgeUnlocked: {
    backgroundColor: '#0f766e',
  },
  healthDayText: {
    color: '#6b7280',
    fontSize: 13,
    fontWeight: '900',
  },
  healthDayTextUnlocked: {
    color: '#ffffff',
  },
  healthTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '900',
  },
  healthBody: {
    color: '#4b5563',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 3,
  },
  healthDisclaimer: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 14,
  },
  modalTitle: {
    color: '#111827',
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 8,
  },
  modalText: {
    color: '#4b5563',
    fontSize: 15,
    lineHeight: 22,
  },
  modalDate: {
    color: '#0f766e',
    fontSize: 15,
    fontWeight: '900',
    marginTop: 10,
  },
  checkRow: {
    borderColor: '#e5e7eb',
    borderTopWidth: 1,
    marginTop: 16,
    paddingTop: 16,
  },
  checkTitle: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 4,
  },
  checkSubtitle: {
    color: '#6b7280',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 6,
  },
  checkCounter: {
    color: '#0f766e',
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 12,
  },
  checkActions: {
    flexDirection: 'row',
    gap: 10,
  },
  keepButton: {
    alignItems: 'center',
    backgroundColor: '#0f766e',
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    paddingVertical: 12,
  },
  keepButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  missButton: {
    alignItems: 'center',
    backgroundColor: '#fff1f2',
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    paddingVertical: 12,
  },
  missButtonText: {
    color: '#be123c',
    fontSize: 15,
    fontWeight: '900',
  },
  closeButton: {
    alignItems: 'center',
    backgroundColor: '#111827',
    borderRadius: 8,
    marginTop: 18,
    paddingVertical: 14,
  },
  closeButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  onboardingScreen: {
    backgroundColor: '#f6f4ee',
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 24,
  },
  languagePicker: {
    alignSelf: 'flex-end',
    backgroundColor: '#e7e5df',
    borderRadius: 12,
    flexDirection: 'row',
    padding: 4,
    zIndex: 2,
  },
  languageOption: {
    borderRadius: 9,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  languageOptionActive: {
    backgroundColor: '#0f766e',
  },
  languageOptionText: {
    color: '#4b5563',
    fontSize: 13,
    fontWeight: '900',
  },
  languageOptionTextActive: {
    color: '#ffffff',
  },
  onboardingContent: {
    justifyContent: 'center',
  },
  onboardingCarousel: {
    flex: 1,
    justifyContent: 'center',
  },
  onboardingPager: {
    flexGrow: 0,
  },
  onboardingIcon: {
    alignItems: 'center',
    backgroundColor: '#e7f4ef',
    borderRadius: 18,
    height: 72,
    justifyContent: 'center',
    marginBottom: 24,
    width: 72,
  },
  onboardingTitle: {
    color: '#111827',
    fontSize: 31,
    fontWeight: '900',
    lineHeight: 40,
  },
  onboardingText: {
    color: '#4b5563',
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 25,
    marginTop: 14,
  },
  onboardingDots: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  onboardingDot: {
    backgroundColor: '#d1d5db',
    borderRadius: 999,
    height: 8,
    width: 22,
  },
  onboardingDotActive: {
    backgroundColor: '#0f766e',
    width: 36,
  },
  onboardingActions: {
    flexDirection: 'row',
    gap: 10,
    paddingBottom: 8,
  },
  undoBar: {
    alignItems: 'center',
    backgroundColor: '#111827',
    borderRadius: 14,
    flexDirection: 'row',
    gap: 12,
    left: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'absolute',
    right: 16,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.22,
    shadowRadius: 18,
  },
  undoText: {
    color: '#ffffff',
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
  },
  undoButton: {
    backgroundColor: '#e08a3c',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  undoButtonText: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '900',
  },
  tabBar: {
    backgroundColor: '#ffffff',
    borderColor: '#d9e3df',
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderTopWidth: 1,
    elevation: 8,
    shadowColor: '#111827',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 10,
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: '800',
  },
});
